# Generated by Django 3.2.19 on 2023-05-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunkoPop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField()),
                ('line', models.PositiveSmallIntegerField(choices=[(1, 'DC'), (2, 'MARVEL'), (3, 'STAR WARS'), (4, 'ANIMATION'), (5, 'GAMES')])),
                ('production_date', models.DateField()),
                ('is_vaulted', models.BooleanField(default=False)),
            ],
        ),
    ]
